### ISSUE TITLE
Third and Fourth section

### ISSUE THREAD

**Issue by 0b51d14n217** [A-116-Coders/Design-Challenge-1#13]
@Preyash-tryin-to-code kindly assign this to me

**Comment by Preyash-tryin-to-code** [comment]
Sure! Go ahead, ATB

**Comment by 0b51d14n217** [comment]
@Preyash-tryin-to-code I've completed the tasks, kindly merge my pull request

**Comment by preyashyadav** [comment]
Merged it! thanks for contributing
